workflows:
  ios-release:
    name: iOS Release Build (.ipa)
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare dependencies and sync CocoaPods
        script: |
          flutter pub get
          cd ios
          rm -rf Flutter/ephemeral/Packages
          pod deintegrate || true
          pod install --repo-update
      - name: Build iOS App (.ipa)
        script: |
          flutter build ipa --release --no-codesign --no-swift-package-manager
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
