// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDN9DyJu-zsXmq66IAUOV4TDoJryv882I',
    appId: '1:242755232702:web:abaeb3c50c626aafa64fef',
    messagingSenderId: '242755232702',
    projectId: 'voicedeceptiongame',
    authDomain: 'voicedeceptiongame.firebaseapp.com',
    storageBucket: 'voicedeceptiongame.firebasestorage.app',
    measurementId: 'G-DYL6SGMX48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQV82td7zSpw47E9XtgMbP0vY3kxgdGJA',
    appId: '1:242755232702:android:2c500a0dc97ead3ea64fef',
    messagingSenderId: '242755232702',
    projectId: 'voicedeceptiongame',
    storageBucket: 'voicedeceptiongame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6Htf5OOA61bYsDdZ0Z2jQWW5kP6jzl8',
    appId: '1:242755232702:ios:cc2b3107c6f068a4a64fef',
    messagingSenderId: '242755232702',
    projectId: 'voicedeceptiongame',
    storageBucket: 'voicedeceptiongame.firebasestorage.app',
    iosBundleId: 'com.example.projectgoogl',
  );
}
